config/routes.rb
OfferMadness::Application.routes.draw do
  resources :offers

  resources :categories

  resources :category_offers

  resources :products

  root :to => 'application#index'

end

app/models/category_offer.rb
class CategoryOffer < ActiveRecord::Base
  attr_accessible :name, :category_ids

  has_many :categories

  def to_s
    name
  end

end

app/controllers/category_offers_controller.rb
class CategoryOffersController < ApplicationController
  before_filter :find_product, only: [:show, :edit, :update, :destroy]

  # GET /category_offers
  # GET /category_offers.json
  def index
    @category_offers = CategoryOffer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @category_offers }
    end
  end

  # GET /category_offers/1
  # GET /category_offers/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category_offer }
    end
  end

  # GET /category_offers/new
  # GET /category_offers/new.json
  def new
    @category_offer = CategoryOffer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category_offer }
    end
  end

  # GET /category_offers/1/edit
  def edit
  end

  # POST /category_offers
  # POST /category_offers.json
  def create
    @category_offer = CategoryOffer.new(params[:category_offer])

    respond_to do |format|
      if @category_offer.save
        format.html { redirect_to @category_offer, notice: 'Category offer was successfully created.' }
        format.json { render json: @category_offer, status: :created, location: @category_offer }
      else
        format.html { render action: "new" }
        format.json { render json: @category_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /category_offers/1
  # PUT /category_offers/1.json
  def update
    respond_to do |format|
      if @category_offer.update_attributes(params[:category_offer])
        format.html { redirect_to @category_offer, notice: 'Category offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_offers/1
  # DELETE /category_offers/1.json
  def destroy
    @category_offer.destroy

    respond_to do |format|
      format.html { redirect_to category_offers_url }
      format.json { head :no_content }
    end
  end

  private

  def find_product
    @category_offer = CategoryOffer.find(params[:id])
  end
end

app/helpers/category_offers_helper.rb
module CategoryOffersHelper
end

app/views/category_offers/_form.html.erb
<%= form_for @category_offer, html: {class: 'form-horizontal'} do |f| %>
  <% if @category_offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_offer.errors.count, "error") %> prohibited this category_offer from being saved:</h2>

      <ul>
      <% @category_offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :category_ids, 'Categories', class: 'control-label' %>
    <div class="controls">
      <%= f.select :category_ids, Category.all.collect{|c|[c.name, c.id]}, {}, multiple: true %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_offers/edit.html.erb
<h1>Editing category_offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_offer %> |
<%= link_to 'Back', category_offers_path %>

app/views/category_offers/index.html.erb
<h1>Listing Category &ndash; offers</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th colspan="3">Actions</th>
  </tr>

<% @category_offers.each do |category_offer| %>
  <tr>
    <td><%= category_offer.name %></td>
    <td><%= link_to 'Show', category_offer %></td>
    <td><%= link_to 'Edit', edit_category_offer_path(category_offer) %></td>
    <td><%= link_to 'Destroy', category_offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category offer', new_category_offer_path %>

app/views/category_offers/new.html.erb
<h1>New category_offer</h1>

<%= render 'form' %>

<%= link_to 'Back', category_offers_path %>

app/views/category_offers/show.html.erb
<p>
  <b>Name:</b>
  <%= @category_offer.name %>
</p>
<p>
  <b>Categories:</b>
  <% @category_offer.categories.collect do |co| %>
   <%= link_to co, category_path(co) %>
  <% end %>
</p>



<%= link_to 'Edit', edit_category_offer_path(@category_offer) %> |
<%= link_to 'Back', category_offers_path %>